version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: news-tunneler-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - POLL_INTERVAL_SEC=900
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL:-}
      - EMAIL_SMTP_SERVER=${EMAIL_SMTP_SERVER:-}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT:-}
      - EMAIL_FROM=${EMAIL_FROM:-}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD:-}
      - NEWSAPI_KEY=${NEWSAPI_KEY:-}
      - ADMIN_TOKEN=${ADMIN_TOKEN:-}
    volumes:
      - ./backend/app.db:/app/app.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - news-tunneler

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: news-tunneler-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000/ws/alerts
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - news-tunneler

networks:
  news-tunneler:
    driver: bridge

volumes:
  db:
    driver: local

